---
- name: Install nginx
  hosts:  centos_nodes,ubuntu_nodes
  become: yes

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest
    - name: Start nginx service
      package:
        name: nginx
        state: started
        enabled: yes 
