---

- name: Strategies example
  hosts: all #linux_nodes
  become: yes
  gather_facts: linux_nodes


  tasks:

    - name: Ping targets
      ping:

    - name: Sleep for 3 seconds
      shell: "sleep 3"

    - name: Uptime
      command: "uptime"
      register: result

    - name: Print uptime information
      debug:
        var: result.stdout